/* Inbox, trend, monitoring, reporting, team and profile views. */
(() => {
  const api = () => window.PulseApi.request;
  const esc = value => window.PulseApp.esc(value);
  const s = () => window.PulseApp.state;
  const fmt = value => new Intl.NumberFormat().format(value || 0);
  const signed = value => `${value >= 0 ? '+' : ''}${Math.round((value || 0) * 100)}%`;
  const dateLabel = value => value ? new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : '—';
  const topics = ['Battery life', 'Camera', 'Price', 'Support', 'Delivery', 'Design'];
  const colors = ['#28764f', '#d8765e', '#5478b8', '#aa6b9a', '#b18331', '#398e91'];
  const head = (eyebrow, title, subtitle) => `<div class="page-head"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p class="muted">${esc(subtitle)}</p></div></div>`;
  const postMarkup = post => window.PulseDashboard.postMarkup(post);

  async function inbox() {
    const state = s();
    const data = await api()(`/inbox?status=${encodeURIComponent(state.inboxFilter)}&sort=${encodeURIComponent(state.inboxSort)}`);
    const mentions = data.mentions || [];
    let selected = mentions.find(post => post.id === state.inboxSelected) || mentions[0];
    state.inboxSelected = selected?.id || null;
    const filters = ['New','Replied','Resolved'].map(status => `<button class="chip ${state.inboxFilter === status ? 'active' : ''}" data-inbox-filter="${status}">${status}</button>`).join('');
    const detail = selected ? `<div class="post-meta"><span class="tone-pill ${esc(selected.label)}">${esc(selected.label)}</span><span>${esc(selected.platform)}</span><span>·</span><span>${esc(selected.topic)}</span><span>·</span><time>${dateLabel(selected.created_at)}</time></div><h2 class="mention-quote">${esc(selected.text)}</h2><div class="small muted">Reply templates</div><div class="template-actions"><button class="chip" data-template="apologize">Apologize</button><button class="chip" data-template="answer">Answer question</button></div><label class="field"><span>Reply</span><textarea id="replyText" class="textarea" placeholder="Write a thoughtful reply…">${esc(state.replyDraft || selected.reply_text || '')}</textarea></label><div class="button-row"><button class="button primary" data-send-reply="${esc(selected.id)}">Send reply</button><button class="button secondary" data-resolve="${esc(selected.id)}">Mark resolved</button></div>` : '<div class="empty-state">No mentions in this filter.</div>';
    return `${head('Listening', 'Mentions inbox', 'Respond to the newest negative and neutral conversations.')}<div class="content-grid inbox-layout"><section class="panel"><div class="section-heading"><div><h2>Recent mentions</h2><p class="muted small">Newest 30 · ${data.total ?? mentions.length} open or updated</p></div><select class="input inbox-sort" id="inboxSort" aria-label="Sort inbox mentions"><option value="newest" ${state.inboxSort==='newest'?'selected':''}>Newest</option><option value="most_liked" ${state.inboxSort==='most_liked'?'selected':''}>Most liked</option><option value="most_negative" ${state.inboxSort==='most_negative'?'selected':''}>Most negative</option></select></div><div class="chip-group inbox-filters">${filters}</div><div class="inbox-list">${mentions.length ? mentions.map(post => `<button class="inbox-item ${selected?.id === post.id ? 'selected' : ''}" data-inbox-item="${esc(post.id)}"><div class="post-meta"><span class="tone-pill ${esc(post.label)}">${esc(post.label)}</span><span>${esc(post.platform)}</span><span>${esc(post.topic)}</span><span class="status-pill ${esc(post.status.toLowerCase())}">${esc(post.status)}</span></div><span class="inbox-text">${esc(post.text)}</span><span class="muted tiny">${dateLabel(post.created_at)}</span></button>`).join('') : '<div class="empty-state">Nothing in this view. Nice work.</div>'}</div></section><section class="panel inbox-detail"><div class="section-heading"><div><h2>Conversation</h2><p class="muted small">Lumen phone · demo workspace</p></div>${selected ? `<span class="status-pill ${esc(selected.status.toLowerCase())}">${esc(selected.status)}</span>` : ''}</div>${detail}</section></div>`;
  }
  function sparkline(values) {
    const max = Math.max(1, ...values), width = 126, height = 40, pad = 3;
    const coords = values.map((value, index) => ({ x: pad+index*(width-pad*2)/Math.max(1,values.length-1), y: height-pad-value/max*(height-pad*2), value }));
    return `<svg class="sparkline" viewBox="0 0 ${width} ${height}" role="img" aria-label="30-day mentions trend"><polyline points="${coords.map(point => `${point.x},${point.y}`).join(' ')}" fill="none" stroke="var(--brand)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>${coords.map((point,index) => `<circle cx="${point.x}" cy="${point.y}" r="2" fill="var(--brand)"><title>Day ${index+1}: ${point.value} mentions</title></circle>`).join('')}</svg>`;
  }
  async function trends() {
    const state = s();
    const data = await api()(`/trends?platform=${encodeURIComponent(state.trendPlatform === 'All' ? '' : state.trendPlatform)}`);
    const rows = data.trends.slice();
    if (state.trendSort === 'mentioned') rows.sort((a,b) => b.mentions-a.mentions);
    else if (state.trendSort === 'negative') rows.sort((a,b) => b.negativeShare-a.negativeShare);
    else rows.sort((a,b) => b.change-a.change);
    const platforms = ['All','X','Reddit','Instagram','YouTube'].map(platform => `<button class="chip ${state.trendPlatform === platform ? 'active' : ''}" data-trend-platform="${platform}">${platform}</button>`).join('');
    return `${head('Listening', 'Trend explorer', 'Compare topic momentum across the Lumen phone conversation.')}<div class="section-heading trend-tools"><div class="chip-group">${platforms}</div><label class="sort-control"><span class="muted small">Sort by</span><select class="input" id="trendSort"><option value="rising" ${state.trendSort==='rising'?'selected':''}>Fastest rising</option><option value="mentioned" ${state.trendSort==='mentioned'?'selected':''}>Most mentioned</option><option value="negative" ${state.trendSort==='negative'?'selected':''}>Most negative</option></select></label></div><div class="trend-list">${rows.map(row => `<article class="trend-row"><div><strong>${esc(row.topic)}</strong><span class="muted tiny">${fmt(row.mentions)} mentions · ${fmt(row.last7)} this week</span></div><div>${sparkline(row.series)}</div><div class="trend-change ${row.change>=0?'up':'down'}"><strong>${signed(row.change)}</strong><span class="muted tiny">vs previous 7d</span></div><div><strong>${Math.round(row.negativeShare*100)}%</strong><span class="muted tiny">negative share</span></div></article>`).join('')}</div>`;
  }
  async function alerts() {
    const state = s();
    const query = new URLSearchParams({ neg_threshold: state.negThreshold, volume_multiplier: state.volumeMultiplier, topic: state.alertTopic === 'All' ? '' : state.alertTopic });
    const result = await api()(`/alerts?${query}`);
    return `${head('Monitoring', 'Alerts', 'Tune the signals that deserve a closer look.')}<div class="content-grid alert-layout"><section class="panel"><h2>Alert thresholds</h2><div class="range-row"><div><label for="negThreshold">Negative share threshold</label><input id="negThreshold" type="range" min="10" max="80" step="5" value="${state.negThreshold}"></div><strong id="negThresholdValue">${state.negThreshold}%</strong></div><div class="range-row"><div><label for="volumeMultiplier">Volume spike multiplier</label><input id="volumeMultiplier" type="range" min="1.1" max="3" step=".1" value="${state.volumeMultiplier}"></div><strong id="volumeMultiplierValue">${Number(state.volumeMultiplier).toFixed(1)}×</strong></div><div class="field"><label for="alertTopic">Topic</label><select class="input" id="alertTopic"><option>All</option>${topics.map(topic => `<option ${state.alertTopic===topic?'selected':''}>${esc(topic)}</option>`).join('')}</select></div><p class="muted tiny">Signals recalculate against a 30-day baseline.</p></section><section class="panel"><div class="section-heading"><div><h2>Triggered days</h2><p class="muted small alert-count">Last 30 days · ${result.alerts.length} signals</p></div></div><div class="alert-list">${result.alerts.length ? result.alerts.slice().reverse().map(item => `<button class="alert-item" data-alert-day="${item.day}"><span><strong>${dateLabel(item.date)}</strong><span class="muted tiny">${item.mentions} mentions · ${signed(item.net)} net</span></span><span class="alert-reasons">${item.reasons.map(reason => reason.type === 'negative-share' ? `Negative share ${reason.value}%` : `Volume ${reason.value}× baseline`).map(esc).join('<br>')}</span></button>`).join('') : '<div class="empty-state">No days meet these thresholds.</div>'}</div></section></div>`;
  }
  async function reports() {
    const state = s();
    const report = await api()(`/reports?days=${state.reportDays}`);
    const ranges = [7,14,30].map(days => `<button class="chip ${state.reportDays===days?'active':''}" data-report-days="${days}">${days} days</button>`).join('');
    return `${head('Workspace', 'Reports', 'A concise readout, ready to share.')}<div class="section-heading report-tools"><div class="chip-group">${ranges}</div><button class="button primary" data-copy-report>Copy summary</button></div><section class="panel"><pre class="report-text" id="reportText">${esc(report.text)}</pre></section>`;
  }
  async function team() {
    const data = await api()('/team');
    const members = data.members || [];
    const owner = data.owner || {};
    return `${head('Workspace', 'Team', 'Manage who can access this listening workspace.')}<section class="panel"><div class="section-heading"><div><h2>Workspace members</h2><p class="muted small">${members.length+1} people</p></div></div><div class="team-member owner-row"><div class="member-ident">${window.PulseApp.avatar(window.PulseApp.profile || owner, true)}<div><strong>${esc(owner.name)} (you)</strong><span class="muted tiny">${esc(owner.email)}</span></div></div><span class="status-pill owner">Owner</span></div>${members.map((member,index) => `<div class="team-member"><div class="member-ident"><span class="avatar" style="background:${colors[(index+2)%colors.length]}">${esc((member.name||'?').charAt(0).toUpperCase())}</span><div><strong>${esc(member.name)}</strong><span class="muted tiny">${esc(member.email)}</span></div></div><select class="input role-select" data-member-role="${member.id}" aria-label="Role for ${esc(member.name)}">${['Admin','Analyst','Viewer'].map(role => `<option ${role===member.role?'selected':''}>${role}</option>`).join('')}</select><button class="icon-button" data-remove-member="${member.id}" aria-label="Remove ${esc(member.name)}" title="Remove member">×</button></div>`).join('')}</section><section class="panel section"><h2>Invite teammate</h2><form id="inviteForm" class="invite-form"><div class="field"><label for="inviteEmail">Email address</label><input class="input" id="inviteEmail" type="email" required placeholder="teammate@example.com"><span id="inviteError" class="field-error"></span></div><div class="field"><label for="inviteRole">Role</label><select class="input" id="inviteRole"><option>Analyst</option><option>Admin</option><option>Viewer</option></select></div><button class="button primary">Send invite</button></form></section>`;
  }
  async function profile() {
    const data = await api()('/profile');
    window.PulseApp.profile = data;
    const notify = data.notifications || {};
    return `${head('Workspace', 'Profile', 'Your identity and notification preferences.')}<div class="content-grid profile-layout"><section class="panel"><div class="profile-hero">${window.PulseApp.avatar(data, true)}<div><h2>${esc(data.name)}</h2><p class="muted">${esc(data.title)}</p><span class="muted tiny">${esc(data.email)}</span></div></div><form id="profileForm"><div class="field"><label for="profileName">Display name</label><input class="input" id="profileName" value="${esc(data.name)}" maxlength="60" required></div><div class="field"><label for="profileTitle">Job title</label><input class="input" id="profileTitle" value="${esc(data.title)}" maxlength="80"></div><div class="field"><label for="profileEmail">Email</label><input class="input" id="profileEmail" value="${esc(data.email)}" readonly></div><div class="field"><span class="field-label">Avatar color</span><div class="color-options">${colors.map(color => `<button type="button" class="color-swatch ${data.avatarColor===color?'selected':''}" style="background:${color}" data-avatar-color="${color}" aria-label="Choose avatar color ${color}" aria-pressed="${data.avatarColor===color}"></button>`).join('')}</div><input type="hidden" id="avatarColor" value="${esc(data.avatarColor)}"></div><div class="field"><span class="field-label">Notifications</span><div class="check-list"><label><input type="checkbox" id="notifySpike" ${notify.spike?'checked':''}> Spike alerts</label><label><input type="checkbox" id="notifyWeekly" ${notify.weekly?'checked':''}> Weekly report</label><label><input type="checkbox" id="notifyTips" ${notify.tips?'checked':''}> Product tips</label></div></div><div class="button-row"><button class="button primary">Save changes</button><button type="button" class="button secondary" data-logout>Sign out</button></div></form></section><section class="panel"><div class="section-heading"><h2>Account stats</h2></div><div class="stats-grid"><div class="stat-box"><strong>${data.repliesSent}</strong><span>Replies sent</span></div><div class="stat-box"><strong>${(await api()('/team')).members.length+1}</strong><span>Team size</span></div><div class="stat-box"><strong>Owner</strong><span>Workspace role</span></div><div class="stat-box"><strong>${esc(data.memberSince)}</strong><span>Member since</span></div></div><div class="demo-note">Profile and account data are stored in the local Pulse database.</div></section></div>`;
  }
  const views = { inbox, trends, alerts, reports, team, profile };
  window.PulseApps = { render: screen => views[screen]() };
})();
